[config]
schemaVersion = "0.0.1"

[package]
namespace = "NotNet"
name = "Cyberhead"
description = "Proof of concept VR mod"
websiteUrl = "https://github.com/NotNite/Cyberhead"

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[publish]
repository = "https://thunderstore.io"
communities = ["bomb-rush-cyberfunk"]
categories = []
